# @package _global_

defaults:
  - _self_
  - datamodule: undc_pc_fight.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: undc_fight.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /home/fubao/dev/my-ndc/logs/train/runs/2023-01-23_00-38-36/checkpoints/last.ckpt