_target_: src.models.undc_module2.UNDCLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 1

net:
  _target_: src.models.components.undc_pc_net.local_pointnet
net_bool: 
  _target_: src.models.components.undc_pc_net.local_pointnet


out_dir: ${hydra:runtime.output_dir}
train_float: True

net_bool_pth: /home/fubao/dev/my-ndc/logs/train/runs/save_bool/net_bool-25.pth